# Generated by Django 4.0.4 on 2022-05-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
