# Generated by Django 4.0.4 on 2022-05-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_login_email_alter_login_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=2)),
                ('Category', models.CharField(max_length=2)),
                ('VegaOps_GitLab_Project_URL', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Contact_Name', models.CharField(max_length=2)),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
