# Generated by Django 4.0.4 on 2022-05-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upload_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
