# Generated by Django 4.0.4 on 2022-05-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_ticket_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Department',
            field=models.CharField(max_length=10),
        ),
    ]
