# Generated by Django 4.0.4 on 2022-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_ticket_category_alter_ticket_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Department',
            field=models.CharField(max_length=100),
        ),
    ]
