# Generated by Django 4.0.4 on 2022-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_ticket_category_alter_ticket_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
